version: "3.4"
services:

    redis:
      image: redis:alpine
      networks:
        - network-dev
    mysql:
      image: mysql:5.7
      user: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root456
        - MYSQL_DATABASE=cookking
        - MYSQL_USER=cookking
        - MYSQL_PASSWORD=cookking456
      ports:
        - "8082:3306"
      volumes:
          - ../data/mysql:/var/lib/mysql
      networks:
        - network-dev
### Nginx Container #########################################
    webserver:
      image: nginx:alpine
      working_dir: /var/www
      volumes:
          - ../projects/:/var/www
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
       - "443:443"
      networks:
        - network-dev
### PHP-fpm Container #########################################
    app:
      build: phpdocker/php-fpm
      working_dir: /var/www
      volumes:
        - ../projects:/var/www
        - ./phpdocker/php-fpm/config/php-ini-overrides.ini:/usr/local/etc/php/99-overrides.ini
      networks:
        - network-dev
### PhpMyAdmin Container #########################################

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - TZ=Europe/Zurich
        - PMA_ARBITRARY=1
        - MYSQL_USER=akal
        - MYSQL_PASSWORD=akal456
        - MYSQL_ROOT_PASSWORD=root456
      ports:
        - "8888:80"
      depends_on:
        - "mysql"
      networks:
        - network-dev

### ElasticSearch Container #################################

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
        - elasticsearch-plugins:/usr/share/elasticsearch/plugins
      environment:
        - cluster.name=symfony-cluster
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - network-dev
### CERTBOT Container #################################
    certbot:
      image: certbot/certbot
      networks:
        - network-dev
#############################################################
##########PORTAINER#########

    agent:
      image: portainer/agent
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/docker/volumes:/var/lib/docker/volumes
      networks:
        - agent_network
    portainer:
      image: portainer/portainer
      command: -H tcp://tasks.agent:9001 --tlsskipverify
      ports:
        - "9000:9000"
        - "8000:8000"
      volumes:
        - portainer_data:/data
      networks:
        - agent_network
networks:
  agent_network:
    driver: bridge
  network-dev:
### Volumes Setup #############################################

volumes:
  elasticsearch-data:
    driver: "local"
  elasticsearch-plugins:
    driver: "local"
  portainer_data: